# Generated by Django 2.1.2 on 2018-10-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_message_user_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
